#!/usr/bin/env bash
# Installing nginx web server

sudo apt-get -qq update

sudo apt-get -y -qq install nginx

# Adjusting the Firewall allowing traffic on port 80
sudo ufw allow 80

# Overwriting existing content in of web
echo "Hello World!" | sudo tee /var/www/html/*html > /dev/null
