#!/usr/bin/env bash
# Configuring server to return 301 permanent redirection when trying to access /redirect_me/ location
    
# Installing nginx web server

sudo apt-get -qq update

sudo apt-get -y -qq install nginx

# Adjusting the Firewall allowing traffic on port 80
sudo ufw allow 80
    
#Allowing sufficient permissions for error logging
sudo chown -R "$USER":"$USER" /var/log/nginx
sudo chmod 755 /var/log/nginx
sudo chmod 644 /var/log/nginx/error.log

sudo sed -i "54i\\\tlocation /redirect_me/ {\nreturn 301;\n\t}"
sudo nginx -s reload
