#!/usr/bin/env bash
# Configuring a new ubuntu machine to have an HAProxy load balancer

# Update packages + install haproxy
sudo apt-get -qq update
sudo apt-get -y -qq install haproxy

# Configuring HAProxy so that it is managed via an init script
sudo sed -i "8i\ENABLED=1" /etc/haproxy/default

# Customizing Config File ( Mainly Adding backend Servers and specifying load balancing algorithm used

mv /etc/haproxy/haproxy.cfg{,.original}

sudo echo "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy
defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	retries 3
	option redispatch
	timeout connect  5000
	timeout client  10000
	timeout server  10000
listen hbnb
	bind *:80
	mode http
	stats enable
	stats uri /haproxy?stats
	stats realm Strictly\ Private
	stats auth Ahmed:Shehab
	balance roundrobin
	server 440666-web-02 54.82.200.213:80 check
	server 440666-web-01 52.3.245.218:80 check
" > /etc/haproxy/haproxy.cfg

# Starting service
sudo service haproxy start
