#!/usr/bin/env bash
# Printing "bad luck" in fourth iteration, "good luck" in eigth iteration and "Best School" for the rest of the 10 iterations

i=1
while ((i <= 10))
do
if ((i == 4))
then
	echo "bad luck"
elif ((i == 8))
then
	echo "good luck"
else
	echo "Best School"
fi
((i++))
done


