#!/usr/bin/env bash
# Printing Numbers from 1 to 20 adding "bad luck from china" after 4, "bad luck from japan" after 9, "bad luck from italy" after 17

i=1
while ((i <= 20))
do
echo "$i"
case "$i" in
	"4")
		echo "bad luck from china"
	;;
	"9")	
		echo "bad luck from japan"
	;;
	"17")	
		echo "bad luck from italy"
	;;
esac
((i++))
done
