#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.*.1/127.0.0.2/g' ~/hosts.new

sudo sed -i '$ a\8.8.8.8\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

